language: ruby
cache: bundler
rvm:
    - 2.1.5
env:
    - DB=postgresql
before_script:
    - psql -c 'drop database social_smarts_test' -U postgres
    - psql -c 'create database social_smarts_test' -U postgres
